/******************************************************************************
* File Name: secure_keys.h
*
* Description: This file contains configuration parameters for the secure HTTP
* server and the server security keys such as server certificate, private key,
* and the root CA (certificate authority) to trust the client.
*
******************************************************************************
* Copyright (2020), Cypress Semiconductor Corporation.
******************************************************************************
* This software, including source code, documentation and related materials
* (“Software”), is owned by Cypress Semiconductor Corporation or one of its
* subsidiaries (“Cypress”) and is protected by and subject to worldwide patent
* protection (United States and foreign), United States copyright laws and
* international treaty provisions. Therefore, you may use this Software only
* as provided in the license agreement accompanying the software package from
* which you obtained this Software (“EULA”).
*
* If no EULA applies, Cypress hereby grants you a personal, nonexclusive,
* non-transferable license to copy, modify, and compile the Software source
* code solely for use in connection with Cypress’s integrated circuit products.
* Any reproduction, modification, translation, compilation, or representation
* of this Software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death (“High Risk Product”). By
* including Cypress’s product in a High Risk Product, the manufacturer of such
* system or application assumes all risk of such use and in doing so agrees to
* indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef SECURE_KEYS_H_
#define SECURE_KEYS_H_

/* HTTPS server certificate. Copy from the HTTPS server certificate
 * generated by OpenSSL (See README.md on how to generate a SSL certificate).
 */
#define keySERVER_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID3zCCAsegAwIBAgIJAPZIHw60Dq+8MA0GCSqGSIb3DQEBCwUAMHsxCzAJBgNV\n"\
"BAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJlbmdhbHVydTEL\n"\
"MAkGA1UECgwCQ1kxFDASBgNVBAsMC0VuZ2luZWVyaW5nMSEwHwYDVQQDDBhteXNl\n"\
"Y3VyZWh0dHBzZXJ2ZXIubG9jYWwwHhcNMjAwODAzMTQwNjA3WhcNMzAwODAxMTQw\n"\
"NjA3WjB7MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQH\n"\
"DAlCZW5nYWx1cnUxCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEh\n"\
"MB8GA1UEAwwYbXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMIIBIjANBgkqhkiG9w0B\n"\
"AQEFAAOCAQ8AMIIBCgKCAQEA0N9yLX/TZyPQfW84hvaTfTimzl46o6q5v7R6DddS\n"\
"YSIlE5cQ4Fx+XBMnfItiUmdDaeVk/GEWn8Z29sjp6ZfZ4T3d4FtODL8DV2GK3kze\n"\
"WZKc5zfeFxaxvpz9xFVyiEGhgwhL0gNLbZOvseFH1JmDzEw017Ug7JR+aqhniayC\n"\
"jSOXZkKa/sT4rWmXhO2V3+FAbAjlNNW18npoQbgbKtPx46jrUsdb6AMhFTKZQp8z\n"\
"J0NsCoxof5/F35RGNcbByb+3HDWwJ1Q4mv2Ybh/MjKVITx08mwatP2SVx3J3AqQx\n"\
"RjmMpr8LgpHfoxEXhwBmJoaFazHZ4n8Km+hZPCH2X3OQtQIDAQABo2YwZDAfBgNV\n"\
"HSMEGDAWgBSvDIj6mT2KEiWrANfaUcjF3+BtsTAJBgNVHRMEAjAAMAsGA1UdDwQE\n"\
"AwIE8DApBgNVHREEIjAgghhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWyHBMCoAG0w\n"\
"DQYJKoZIhvcNAQELBQADggEBAGzIlAuuq6E2h9CjcVJl81ClKSu52+fUM4N1zB43\n"\
"cQnOKk2quMp/w0uqaG5bb4y2fLYl6VfZqTyttlMaE/uRehJqd2/nEHb0oTFbe4PZ\n"\
"Q06VONOXtIi0B85KlVQSUAYy5fTgv7K46tEiw6s7JPGJXlEACytJ+MtDIYjIaq9c\n"\
"xCNTRYRZt3w+Qk+jBrW5itPPjaVc4IRl7wiV5hnKkAl6rJ2QdxcOFn6t5X7Rqac7\n"\
"reDUYrx+QAdsJa/hiaOGZy6JXDZUxTbhZhzJ8H5d5u5sZOpYaZb7rTRgtviuFQws\n"\
"fgx2Op7XYX7qqEaH+lTlBLS4Y9OQnjZauqPK0kjjnWs98Q8=\n"\
"-----END CERTIFICATE-----"

/* Private key of the HTTPS server. Copy from the HTTPS server key
 * generated by OpenSSL (See README.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN RSA PRIVATE KEY-----\n"\
"MIIEowIBAAKCAQEA0N9yLX/TZyPQfW84hvaTfTimzl46o6q5v7R6DddSYSIlE5cQ\n"\
"4Fx+XBMnfItiUmdDaeVk/GEWn8Z29sjp6ZfZ4T3d4FtODL8DV2GK3kzeWZKc5zfe\n"\
"Fxaxvpz9xFVyiEGhgwhL0gNLbZOvseFH1JmDzEw017Ug7JR+aqhniayCjSOXZkKa\n"\
"/sT4rWmXhO2V3+FAbAjlNNW18npoQbgbKtPx46jrUsdb6AMhFTKZQp8zJ0NsCoxo\n"\
"f5/F35RGNcbByb+3HDWwJ1Q4mv2Ybh/MjKVITx08mwatP2SVx3J3AqQxRjmMpr8L\n"\
"gpHfoxEXhwBmJoaFazHZ4n8Km+hZPCH2X3OQtQIDAQABAoIBABUyiAjcDx1JgjAo\n"\
"qGjx/zfXFv6ci4Duo5kz/KsI7iBTccXSL/FFEcHQY9J85saMGkhV8nC2fbBLWOlk\n"\
"rHB7a64zNCA/w+UBQZqNmKVE0c/vVCMXBV/8ep9omUxii5QObRC6N8+ha/c75Lm9\n"\
"rieCSODj3v0BMc0wqL+0RYWwTzN5eT4SMyHZo40qqWCzPfHDGgpBy4sSXh2ORF84\n"\
"6GZht+onUtQrMErxyJz5h6gMWner+wAsBgWT9Oov4A1sX0FeTRrfffvJ4BkaLjQD\n"\
"WpqN4nKpC3Rkw6NvSKEcGbTiYQ+iVfuMr19/WTqnM46lPK/61BephDEVMbAu1+kr\n"\
"bNUwJuECgYEA74znFXDMKNMDRMbHuzse0T0puCLLd45lSf84x0cNNY28fWV+Vh+0\n"\
"o1XLbvkRM2dT4HkKs8z2RFtZQ1SMpychIBndkOo2bcnbO8uAeXU0nJtY/I2PFyV4\n"\
"mynAQqnZelUj5opUn0P53JHZBII2R+jRjqhSyaG+pUOyH20RuHo4pD0CgYEA3zdB\n"\
"1zq503qM3qRCKIJ2djaJqG//ptGI3J1c0Pj64PvFDemqndpk6OA61qAUsh0QvI+U\n"\
"yicFBGrCBstZGen1mTwiR4cGAm++HvdRgvorKCjMDzD8Qv4iep6+6dR1WEsPWeeB\n"\
"DuXsKaJ3JuyWQjilEIfrRUUMMUCinH9zxyrSTdkCgYA5C+4QDg+gfTffDhOMg/S/\n"\
"0Xf48NhRfWijqZLk6ge8RCeqGRxv+Bb1er36jHfLLQUthMXGsb3H45UrUpw4Rjo+\n"\
"Qcqg8xXJKXP7FmhfBElmLhyP8EouMe85zESL25T96/6jrTefwfljzJvI1hWFJG2b\n"\
"MnycpdcX1jo5/6hjrT+F5QKBgQDFirJzFp7D4I3wr295SFQsNAHJliyq5n73tzAg\n"\
"JGhqWYY/1M5Q2qk5Ss/nh04pfv2D0pG8AaI4EX7a4nVdMKdQ0F4J7R3NZDTeVMPH\n"\
"ZTxyUwCcZR6q7xt2ZyzP5V1gITVZvD6D/8jr48MNKI2l11mFcrQs3nl20RvX4heF\n"\
"aIkrqQKBgE0z8BMROgCSprJiQoFVBWQq5cY+AbkkcS2PyS+Ynft5dAEF0ev+ubC3\n"\
"SE/BVvoJj95CZRLyG3EwqjTiamO9OrMQuHpYaKimJ5XYI7dQuY1+gGl8vj74Bj6H\n"\
"n9vMu+gL1W6BFVcWHzRBhWXd6kdnfYG2meoVvqPaxGdlXIGC+0Fe\n"\
"-----END RSA PRIVATE KEY-----"

/* HTTPS client certificate. In this example this is the RootCA
 * certificate so as to verify the HTTPS client's identity. */
#define keyCLIENT_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIIDyTCCArGgAwIBAgIJAPMTyp8blMu4MA0GCSqGSIb3DQEBCwUAMHsxCzAJBgNV\n"\
"BAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJlbmdhbHVydTEL\n"\
"MAkGA1UECgwCQ1kxFDASBgNVBAsMC0VuZ2luZWVyaW5nMSEwHwYDVQQDDBhteXNl\n"\
"Y3VyZWh0dHBzZXJ2ZXIubG9jYWwwHhcNMjAwODAzMTQwNjA0WhcNMzAwODAxMTQw\n"\
"NjA0WjB7MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQH\n"\
"DAlCZW5nYWx1cnUxCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEh\n"\
"MB8GA1UEAwwYbXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMIIBIjANBgkqhkiG9w0B\n"\
"AQEFAAOCAQ8AMIIBCgKCAQEAnriQLWlzQS5vizPvfsvgkUkXy/xhPT59KiVfc2Cp\n"\
"U/Bp0ewcM30cSc6EQrskPR768kCFgkIdhMoJIDyY8vaQFA81W78fsUCucktk7Rt6\n"\
"DYc8g3r1fQVOYN4cj3/tng5wOCJ/riFtjiFeb7DhnmOkTDTv7+HlVGq9srGw26VW\n"\
"Gmnx0KJ9+Ve/W0jhuhQ3CWU+AvnFjD2I4dSk+dQ4cHXAmHrfPpZLeU/DpRPPMD43\n"\
"/dQYMCcqcsgiaDVuGAdplE3BNOAApMrHnOmvw0sMW85FrFtucV9ZPtKF9bbr7x6N\n"\
"z+sdGbROcH6Eu97lX6AinkqrsPBOzma8RFQ8oHRwBag4KwIDAQABo1AwTjAdBgNV\n"\
"HQ4EFgQUrwyI+pk9ihIlqwDX2lHIxd/gbbEwHwYDVR0jBBgwFoAUrwyI+pk9ihIl\n"\
"qwDX2lHIxd/gbbEwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEARtW7\n"\
"+a7xnqlCnWsRsqC2EBbgs316vd7on5hPlNBP0jNbZ0sW2Ep5rw9xs08pm0xcsx+j\n"\
"ybT3XA9YMFZMnPDK6gj4/aFp/li3pqvYlWWhz9Jm3OIWLIdsd4hGLitt+nWBQSgp\n"\
"43toPLVT2HarLUNcG27HV6BGOtoinmE6qeWi5bRW9YcVQKR+/VUQM4+wisClNYL/\n"\
"muuyOe3ESRt4B2gkO4xsP3ZApyAU4PSZ79WSfaObakbVQnUMcef4Bv9CYjLnFs+N\n"\
"N1HfVssMA6bO2lpu6oKCOBAMQzyGhnUqa8lpPNDMiarYX/xm1Qu4QQfERyqpa09a\n"\
"ueQF07ekTM62du8YhQ==\n"\
"-----END CERTIFICATE-----"

#endif /* SECURE_KEYS_H_ */


/* [] END OF FILE */

